spring:
  application:
    name: chroniqo
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    #driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    #show-sql: true
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: validate
        #format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.tool.schema: debug