spring:
  application:
    name: chroniqo
    version: ${APP_VERSION}
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: validate
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    remember-me:
      key: ${REMEMBER_ME_KEY}
      use-secure-cookie: ${REMEMBER_ME_SECURE_COOKIE_ENABLED:true}
      validity: P30D
      cookie-domain: ${REMEMBER_ME_COOKIE_DOMAIN:localhost}